# PHP CircleCI 2.0 configuration file
# See: https://circleci.com/docs/2.0/language-php/
defaults: &defaults
  docker:
    - image: cimg/php:8.1.11

version: 2

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    <<: *defaults

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # Using the RAM variation mitigates I/O contention
      # for database intensive operations.
      # - image: circleci/mysql:5.7-ram
      #
      # - image: redis:2.8.19

    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run: sudo apt update # PHP CircleCI 2.0 Configuration File# PHP CircleCI 2.0 Configuration File sudo apt install zlib1g-dev libsqlite3-dev
      - run: sudo docker-php-ext-install zip

  setup-app:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: "Install composer dependencies"
          command: composer install -n --prefer-dist
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run:
          name: "Generate app keys and storage link"
          command: |
            mv .env.pipelines .env
            php artisan key:generate
            chmod -R 777 storage bootstrap/cache
            php artisan storage:link

  analysis:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Run static analysis
          command: ./vendor/bin/phpstan analyze --memory-limit=1G

      - run:
          name: Run code style fixer
          command: ./vendor/bin/pint

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: "Create database and run migrations"
          env:
            DB_CONNECTION: sqlite
            DB_DATABASE: database/database.sqlite
          command: |
            touch database/database.sqlite
            php artisan migrate --env=testing
      - run:
          name: "Run automated tests"
          env:
            DB_CONNECTION: sqlite
            DB_DATABASE: database/database.sqlite
          command: ./vendor/bin/pest --parallel

workflows:
  version: 2
  build-setup-test:
    jobs:
      - build
      - setup-app:
          requires:
            - build
      - analysis:
          requires:
            - setup-app
      - test:
          requires:
            - setup-app
